import { Routes, Route, Link } from 'react-router-dom'
import { motion } from 'motion/react'
import { ArrowUpRight, ArrowRight, AudioLines, Check, FileText, ShieldCheck, Sparkles, ChevronDown } from 'lucide-react'
import { Button } from './components/ui/button'
import { Waveform } from './components/Waveform'
import Workspace from './Workspace'

export function Brand(){return <Link to="/" className="brand" aria-label="Resonant home"><span className="brand-symbol"><AudioLines size={23}/></span>resonant<span className="brand-dot">®</span></Link>}
const reveal={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true},transition:{duration:.65}}

function Landing(){return <div className="landing">
  <a className="skip-link" href="#main">Skip to content</a>
  <header className="site-nav container"><Brand/><nav aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="#intelligence">The intelligence</a></nav><Button asChild variant="secondary"><Link to="/workspace">Open workspace <ArrowUpRight size={16}/></Link></Button></header>
  <main id="main">
    <section className="hero container">
      <motion.div {...reveal} className="hero-copy"><div className="eyebrow"><span className="status-dot"/> A CLEARER SIGNAL IN EVERY CALL</div><h1>Every conversation.<br/><span>A little more clarity.</span></h1><p>Go beyond the recording. Turn support calls into<br className="desktop-break"/> meaningful summaries, quality insights, and clear next steps.</p><div className="hero-actions"><Button asChild><Link to="/workspace">Analyze a call <ArrowUpRight size={18}/></Link></Button><Link className="text-link" to="/workspace?sample=billing-refund">Explore a sample <ArrowRight size={16}/></Link></div><div className="hero-note"><ShieldCheck size={14}/> Evidence-led insights. Human judgment at the center.</div></motion.div>
      <div className="signal-scene"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="signal-label">THE CONVERSATION, REIMAGINED</span><Waveform/><div className="signal-footer"><span><span className="status-dot"/> FROM VOICE TO UNDERSTANDING</span><span>01 — 05</span></div></div>
      <motion.div {...reveal} className="preview-card"><div className="preview-heading"><span className="icon-tile"><Sparkles size={17}/></span><span>Clarity, at a glance<small>Illustrative result · Billing support</small></span><span className="badge">Resolved</span></div><div className="preview-grid"><div><span className="micro-label">THE SHORT VERSION</span><p>A duplicate charge, acknowledged.<br/>A refund issued. A customer reassured.</p><div className="tags"><span>Billing</span><span>Refund initiated</span><span>Follow-up</span></div></div><div className="preview-score"><span className="micro-label">SERVICE QUALITY</span><div><strong>4.8</strong><span>/ 5</span><span className="score-bars">▂▃▅▆█</span></div><small>Grounded in the conversation</small></div></div></motion.div>
      <a href="#how-it-works" className="scroll-cue">THERE’S MORE TO EVERY CALL <ChevronDown size={14}/></a>
    </section>
    <section id="how-it-works" className="process-section container"><motion.div {...reveal} className="section-heading"><div><span className="eyebrow">LESS REPLAYING. MORE UNDERSTANDING.</span><h2>From the first word<br/>to the next best step.</h2></div><p>Five focused agents work together to make<br/>the details useful, and the bigger picture clear.</p></motion.div><div className="process-grid">{[[AudioLines,'01','Bring the conversation','Upload a recording or transcript. Start with what you already have.'],[FileText,'02','Find what matters','Transcribe the call and surface its issue, outcome, and next steps.'],[ShieldCheck,'03','See the evidence','Explore quality scores backed by the exact words in the call.']].map(([Icon,n,title,body])=>{const I=Icon as typeof AudioLines;return <motion.article {...reveal} key={String(n)}><div className="process-top"><I size={25}/><span>{String(n)}</span></div><h3>{String(title)}</h3><p>{String(body)}</p></motion.article>})}</div></section>
    <section id="intelligence" className="intelligence container"><motion.div {...reveal} className="intelligence-copy"><span className="eyebrow">BUILT FOR THE MOMENTS THAT MATTER</span><h2>More context.<br/><span>Better conversations.</span></h2><p>A score is only useful when you know why. Trace every assessment back to the transcript, review what’s uncertain, and keep the next action in sight.</p><ul>{['Structured summaries, without the guesswork','Four quality dimensions, with supporting evidence','Call history that keeps each conversation distinct'].map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul><Button asChild variant="secondary"><Link to="/workspace">Find your signal <ArrowUpRight size={16}/></Link></Button></motion.div><motion.div {...reveal} className="evidence-preview"><div className="micro-label"><ShieldCheck size={15}/> QUALITY, WITH CONTEXT <span>ILLUSTRATIVE</span></div><div className="evidence-score"><h3>Empathy</h3><span>5 <small>/ 5</small></span></div><div className="meter"><i style={{width:'100%'}}/></div><p>The agent acknowledges the inconvenience before offering a clear resolution.</p><blockquote>“I’m sorry for the confusion. I can see two charges for the same period.”<footer>AGENT · SEGMENT 02</footer></blockquote><span className="evidence-foot"><Check size={14}/> Every insight starts with evidence</span></motion.div></section>
    <section className="closing container"><span className="eyebrow">LISTEN LESS. UNDERSTAND MORE.</span><h2>Your next call has a story.<br/>Let’s make it clear.</h2><Button asChild><Link to="/workspace">Open your workspace <ArrowUpRight size={18}/></Link></Button></section>
  </main><footer className="site-footer container"><Brand/><span>Every conversation, understood.</span><small>Resonant · Call intelligence</small></footer>
</div>}
export default function App(){return <Routes><Route path="/" element={<Landing/>}/><Route path="/workspace" element={<Workspace/>}/><Route path="*" element={<div className="not-found"><h1>Page not found</h1><Link to="/">Return home</Link></div>}/></Routes>}
